### create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "jhangmu@tech.com",
    "password": "1234"
}

### sign in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "jhangmu@tech.com",
    "password": "1234"
}

### getting logged in user
GET http://localhost:3000/auth/loggedinuser


### logout user
POST http://localhost:3000/auth/logOut

### find user individually
GET  http://localhost:3000/auth/3

### find all user
GET http://localhost:3000/auth?email=jane@tech.com

###delete a user
DELETE http://localhost:3000/auth/5

###update a user
PATCH  http://localhost:3000/auth/4
content-type: application/json

{
    "email": "Julia@tech.com"
}

###create a report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Hilux",
    "year": 1980,
    "mileage": 1000000,
    "lng": 0,
    "lat": 0,
    "price": 100000,
}